// This file is auto-generated by GitHub Actions during deployment.
// For local development, you can set your Apps Script URL here.
window.CONFIG = {
  APPS_SCRIPT_URL: "" // Insert your local Apps Script URL for testing
};
